// Created by DatenMeister.SourcecodeGenerator.TypeScriptInterfaceGenerator Version 1.3.0.0
export namespace _Root
{
        export class _SwimlaneConfiguration
        {
            static verticalSwimlaneProperty = "verticalSwimlaneProperty";
            static horizontalSwimlaneProperty = "horizontalSwimlaneProperty";
            static cellContent = "cellContent";
            static linkContent = "linkContent";
            static _name_ = "name";
        }

        export const __SwimlaneConfiguration_Uri = "dm:///intern.types.swimlane.datenmeister/#e92b2227-9b93-4033-ac2e-772a2230a869";
        export class _SwimlaneViewDefinition
        {
            static _name_ = "name";
            static swimlaneConfiguration = "swimlaneConfiguration";
            static viewNode = "viewNode";
        }

        export const __SwimlaneViewDefinition_Uri = "dm:///intern.types.swimlane.datenmeister/#1c8b02e8-1988-4c3b-9d74-8739c400d56c";
        export class _SwimlaneRenderAction
        {
            static swimlaneViewDefinition = "swimlaneViewDefinition";
        }

        export const __SwimlaneRenderAction_Uri = "dm:///intern.types.swimlane.datenmeister/#83f81e3a-7d9a-4c27-9759-994f796a5bc8";
        export class _SwimlaneForm
        {
            static swimlaneViewDefinition = "swimlaneViewDefinition";
            static _name_ = "name";
            static title = "title";
            static isReadOnly = "isReadOnly";
            static isAutoGenerated = "isAutoGenerated";
            static hideMetaInformation = "hideMetaInformation";
            static originalUri = "originalUri";
            static originalWorkspace = "originalWorkspace";
            static creationProtocol = "creationProtocol";
        }

        export const __SwimlaneForm_Uri = "dm:///intern.types.swimlane.datenmeister/#142cb4a2-9a07-4e63-a212-32b0a1f0a289";
}

