using DatenMeister.Core.EMOF.Interface.Reflection;
using DatenMeister.Core.Models;
using DatenMeister.Core.Uml.Helper;
using DatenMeister.Forms.Fields;
using DatenMeister.Forms.FormFactory;
using DatenMeister.Forms.Helper;

namespace DatenMeister.Forms.RowForm;

public class RowFormFromData : INewRowFormFactory
{
    public void CreateRowForm(RowFormFactoryParameter parameter, NewFormCreationContext context,
        FormCreationResult result)
    {
        if (result.IsMainContentCreated)
            return;
        
        var element = parameter.Element;
        var parameterMetaClass = parameter.MetaClass;

        var createdForm =
            result.Form ??= context.Global.Factory.create(_Forms.TheOne.__RowForm);

        if (parameterMetaClass != null)
        {
            var name = NamedElementMethods.GetName(parameterMetaClass);
            createdForm.set(_Forms._RowForm.name, $"{name} - Detail");
            createdForm.set(_Forms._RowForm.isAutoGenerated, true);

            FormMethods.AddToFormCreationProtocol(
                createdForm,
                "[FormCreator.CreateRowFormByMetaClass]: " + NamedElementMethods.GetName(parameterMetaClass));

            if (!FieldCreationHelper.AddFieldsToRowOrTableFormByMetaClass(createdForm, parameterMetaClass, context))
            {
                createdForm.set(_Forms._RowForm.allowNewProperties, true);
            }

            // TODO: CleanupRowForm(createdForm);
            result.IsManaged = result.IsMainContentCreated = true;
        }
        else
        {


            createdForm.set(_Forms._RowForm.name, "Item");
            createdForm.set(_Forms._RowForm.isAutoGenerated, true);

            result.AddToFormCreationProtocol(
                "[RowFormFromData.CreateRowFormForItem]: " + NamedElementMethods.GetName(element));

            var metaClass = (element as IElement)?.metaclass;
            if (metaClass != null)
            {
                FieldCreationHelper.AddFieldsToRowOrTableFormByMetaClass(createdForm, metaClass, context);
                result.IsManaged = result.IsMainContentCreated = true;
            }

            // TODO CleanupRowForm(createdForm);
        }
    }
}