using DatenMeister.Core.EMOF.Interface.Reflection;
using DatenMeister.Core.Models;
using DatenMeister.Core.Uml.Helper;
using DatenMeister.Forms.Fields;
using DatenMeister.Forms.FormFactory;

namespace DatenMeister.Forms.RowForm;

public class RowFormFromData : IRowFormFactory
{
    public void CreateRowForm(RowFormFactoryParameter parameter, FormCreationContext context,
        FormCreationResultMultipleForms result)
    {
        if (result.IsMainContentCreated)
            return;
        
        var element = parameter.Element;
        var parameterMetaClass = parameter.MetaClass;

        if (!result.Forms.Any())
        {
            result.Forms.Add(context.Global.Factory.create(_Forms.TheOne.__RowForm));
        };
        
        var createdForm = result.Forms.First();

        if (parameterMetaClass != null)
        {
            var name = NamedElementMethods.GetName(parameterMetaClass);
            createdForm.set(_Forms._RowForm.name, $"{name} - Detail");
            createdForm.set(_Forms._RowForm.isAutoGenerated, true);

            result.AddToFormCreationProtocol(
                "[FormCreator.CreateRowFormByMetaClass]: " + NamedElementMethods.GetName(parameterMetaClass));

            if (!FieldCreationHelper.AddFieldsToRowOrTableFormByMetaClass(createdForm, parameterMetaClass, context))
            {
                createdForm.set(_Forms._RowForm.allowNewProperties, true);
            }

            // TODO: CleanupRowForm(createdForm);
            result.IsManaged = result.IsMainContentCreated = true;
        }
        else
        {
            createdForm.set(_Forms._RowForm.name, "Item");
            createdForm.set(_Forms._RowForm.isAutoGenerated, true);

            result.AddToFormCreationProtocol(
                "[RowFormFromData.CreateRowFormForItem]: " + NamedElementMethods.GetName(element));

            var metaClass = (element as IElement)?.metaclass;
            if (metaClass != null)
            {
                FieldCreationHelper.AddFieldsToRowOrTableFormByMetaClass(createdForm, metaClass, context);
                result.IsManaged = result.IsMainContentCreated = true;
            }

            // TODO CleanupRowForm(createdForm);
        }
    }
}