import * as FormActions from "../FormActions.js";
import {FormType, IFormNavigation} from "../forms/Interfaces.js";
import * as Mof from "../Mof.js";
import {SubmitMethod} from "../forms/Forms.js";
import * as _DatenMeister from "../models/DatenMeister.class.js";
import * as ClientForm from "../client/Forms.js"
import * as ViewModeLogic from "../forms/ViewModeLogic.js"
import * as ObjectForm from "../forms/ObjectForm.js"

export function loadModules() {
    FormActions.addModule(new RenderHtml());
    FormActions.addModule(new RenderForm());
}

const divIdOfRenderArea = '#pageContent';

class RenderHtml extends FormActions.ItemFormActionModuleBase {
    constructor() {
        super("DatenMeister.Render.Html", _DatenMeister._Actions._ClientActions.__RenderHtmlClientAction_Uri);
    }

    async execute(form: IFormNavigation, element: Mof.DmObject, parameter?: Mof.DmObject, submitMethod?: SubmitMethod): Promise<void> {
        const html = element.get(_DatenMeister._Actions._ClientActions._RenderHtmlClientAction.html, Mof.ObjectType.String);
        if(html !== undefined && html !== "" && html !== null)
        {
            $(divIdOfRenderArea).html(html);
            return;
        }
        
        const text = element.get(_DatenMeister._Actions._ClientActions._RenderHtmlClientAction.text, Mof.ObjectType.String);
        if(text !== undefined && text !== "" && text !== null)
        {
            $(divIdOfRenderArea).text(text);
            return;
        }
        
        $(divIdOfRenderArea).text("ClientActions.RenderHtml: Neither html nor text was set");
    }
}

class RenderForm extends FormActions.ItemFormActionModuleBase
{
    constructor() {
        super("DatenMeister.Render.Form", _DatenMeister._Actions._ClientActions.__RenderFormClientAction_Uri);
    }
    
    async execute(form: IFormNavigation, element: Mof.DmObject, parameter?: Mof.DmObject, submitMethod?: SubmitMethod): Promise<void> {
        const dataWorkspace = element.get(_DatenMeister._Actions._ClientActions._RenderFormClientAction.dataWorkspaceId , Mof.ObjectType.String);
        const dataUri = element.get(_DatenMeister._Actions._ClientActions._RenderFormClientAction.dataUri , Mof.ObjectType.String);
        const formAutogenerate = element.get(_DatenMeister._Actions._ClientActions._RenderFormClientAction.formAutoGenerate, Mof.ObjectType.Boolean);
        const formType = element.get(_DatenMeister._Actions._ClientActions._RenderFormClientAction.formType, Mof.ObjectType.String);
        
        // Ok, we have consolidated the information. 
        if(!formAutogenerate)
        {
            throw new Error("Only Form autogenerate is implemented yet");
        }
        
        let createdForm: Mof.DmObjectWithSync | undefined;
        
        // Get the autogenerated form
        switch(formType)
        {
            case _DatenMeister._Forms._FormTypes._FormType.Object:
                createdForm = await ClientForm.getObjectFormForItem(
                    dataWorkspace, dataUri, ViewModeLogic.ViewModes.Default);


                if(createdForm === undefined) {
                    throw new Error("Could not load form from server");
                }
                
                const container = new ObjectForm.ObjectFormHtmlElements();
                container.itemContainer = $("#pageContent");
                
                const objectForm = new ObjectForm.ObjectFormCreator(container);
                await objectForm.createFormByObject(
                    {
                        isReadOnly : true, 
                        formType: FormType.Object,
                        viewMode: ViewModeLogic.ViewModes.Default
                    });
                
                break;
            case _DatenMeister._Forms._FormTypes._FormType.Collection:
                createdForm = await ClientForm.getCollectionFormForExtent(
                    dataWorkspace, dataUri, ViewModeLogic.ViewModes.Default);
                break;
            default: 
                throw new Error("Unknown form type: " + formType);
        }
    }
}