using DatenMeister.Core.EMOF.Interface.Reflection;
using DatenMeister.Core.Models;
using DatenMeister.Core.Uml.Helper;
using DatenMeister.Forms.Fields;
using DatenMeister.Forms.FormFactory;
using DatenMeister.Forms.Helper;

namespace DatenMeister.Forms.TableForms;

public class TableFormForMetaClass : ITableFormFactory
{
    /// <summary>
    /// Creates the Table Form
    /// </summary>
    /// <param name="parameter"></param>
    /// <param name="context"></param>
    /// <param name="result"></param>
    public void CreateTableForm(
        TableFormFactoryParameter parameter,
        FormCreationContext context,
        FormCreationResult result)
    {
        if (result.IsMainContentCreated)
            return;
        
        var metaClass = parameter.MetaClass;

        if (metaClass != null)
        {
            result.Form ??= context.Global.Factory.create(_Forms.TheOne.__TableForm);
            result.Form.set(_Forms._TableForm.isAutoGenerated, true);

            result.AddToFormCreationProtocol(
                "[TableFormFromData.CreateTableFormForProperty]");

            FieldCreationHelper.AddFieldsToRowOrTableFormByMetaClass(result.Form, metaClass, context);
            result.Form.set(_Forms._TableForm.metaClass, metaClass);

            result.IsManaged = result.IsMainContentCreated = true;
        }
    }
}