using DatenMeister.Core.Interfaces.Workspace;
using DatenMeister.Core.Models;
using DatenMeister.Forms.Fields;
using DatenMeister.Forms.FormFactory;

namespace DatenMeister.Forms.TableForms;

public class TableFormForMetaClass (IWorkspaceLogic workspaceLogic): FormFactoryBase, ITableFormFactory
{   
    /// <summary>
    /// Creates a table form for the given meta class and adds it to the result. The created form is
    /// configured to reflect the properties of the specified meta class and is marked as autogenerated.
    /// This method ensures the form is added to the main content if it is not already created.
    /// </summary>
    /// <param name="parameter">The parameter object containing details for the table form creation,
    /// including the meta class.</param>
    /// <param name="context">The context of the form creation process, containing global configuration
    /// and settings.</param>
    /// <param name="result">The result object to which the created or updated forms are added, and
    /// which tracks the state of the form creation process.</param>
    public void CreateTableForm(
        TableFormFactoryParameter parameter,
        FormCreationContext context,
        FormCreationResultMultipleForms result)
    {
        if (result.IsMainContentCreated)
            return;
        
        var metaClass = parameter.MetaClass;

        if (metaClass == null)
        {
            return;
        }

        if (result.Forms.Count == 0)
        {
            result.Forms.Add(context.Global.Factory.create(_Forms.TheOne.__TableForm));
        };
        
        var createdForm = result.Forms.First();
        createdForm.set(_Forms._TableForm.isAutoGenerated, true);

        result.AddToFormCreationProtocol(
            "[TableFormFromData.CreateTableFormForProperty]");

        FieldCreationHelper.AddFieldsToRowOrTableFormByMetaClass(workspaceLogic, createdForm, metaClass, parameter, context);
        createdForm.set(_Forms._TableForm.metaClass, metaClass);

        result.IsManaged = result.IsMainContentCreated = true;
    }
}