import * as FormActions from '/js/datenmeister/FormActions.js';
import * as Mof from "/js/datenmeister/Mof.js";
import {SubmitMethod} from "/js/datenmeister/forms/Forms.js";
import * as ClientElements from "/js/datenmeister/client/Elements.js"
import * as ClientItems from "/js/datenmeister/client/Items.js"
import * as DmModel from '/js/datenmeister/models/DatenMeister.class.js';
import * as FormInterfaces from '/js/datenmeister/forms/Interfaces.js';
import * as FormFactory from "/js/datenmeister/forms/FormFactory.js";
import {IDecoupledFormConfiguration} from "/js/datenmeister/forms/IFormConfiguration.js";
import * as QueryEngine from "/js/datenmeister/modules/QueryEngine.js";
import * as TableForm from "/js/datenmeister/forms/TableForm.js";
import {StaticObjectQuery} from "/js/datenmeister/modules/StaticObjectQuery.js";

export function init()
{
    FormActions.addModule(new ViewNodeRenderAction());
    FormFactory.registerDecoupledForm(_Root.__ViewDataTable_Uri, () => new ViewNodeRenderForm());
}

class ViewNodeRenderAction
    extends FormActions.ItemFormActionModuleBase
    implements FormActions.IItemFormActionModule
{
    constructor() {
        super();
        this.actionName = "DatenMeister.ViewNodes.RenderItemsInPopup";
    }

    async execute(form?: FormInterfaces.IFormNavigation, 
                  element?: Mof.DmObject, 
                  parameter?: Mof.DmObject,
                  submitMethod?: SubmitMethod): Promise<Mof.DmObject | void> {
        if(element === undefined) throw new Error("element is null");
        
        // We have to create the temporary action on the server to navigate to it. 
        const temporaryItemResult = await ClientElements.createTemporaryElement(_Root.__ViewNodeRenderAction_Uri);
        await ClientItems.setPropertyReference(temporaryItemResult.workspace, temporaryItemResult.uri,
            {
                property:_Root._ViewNodeRenderAction.viewNode,
                referenceUri: element.uri
            });
        
        // Now open the popup window
        const createWindow = new Mof.DmObject(DmModel._Actions._ClientActions.__NavigateOpenActionInWindow_Uri);
        createWindow.set(DmModel._Actions._ClientActions._NavigateOpenActionInWindow.context, "render");
        createWindow.set(DmModel._Actions._ClientActions._NavigateOpenActionInWindow.actionUrl, temporaryItemResult.uri);
        createWindow.set(DmModel._Actions._ClientActions._NavigateOpenActionInWindow.workspaceId, temporaryItemResult.workspace);

        await FormActions.executeClientAction(createWindow);
        return Promise.resolve(undefined);
    }
}

class ViewNodeRenderForm implements FormInterfaces.IDecoupledForm
{
    async createForm(parent: JQuery<HTMLElement>, configuration: IDecoupledFormConfiguration): Promise<void> {
        const viewNode = configuration.form.get(_Root._ViewDataTable.viewNode, Mof.ObjectType.Object);
        if (viewNode === undefined)
            throw new Error("ViewNode is undefined");

        const query = new QueryEngine.QueryBuilder();
        QueryEngine.referenceExistingNode(query, viewNode.workspace, viewNode.uri);

        const viewData = await ClientElements.queryObject(query.queryStatement);

        const tableFormObject = configuration.form.get(_Root._ViewDataTable.tableForm, Mof.ObjectType.Object);
        const tableForm = new TableForm.TableForm({
            formElement: tableFormObject,
            isReadOnly: true,
            formType: FormInterfaces.FormType.Collection
        });
        
        tableForm.tableParameter.hideButtonsForNewElements = true;
        tableForm.tableParameter.allowSortingOfColumn = true;
        tableForm.tableParameter.allowFilteringOnProperty = true;
        tableForm.tableParameter.allowFreeTextFiltering = true;
        tableForm.tableParameter.showFilterQuery = true;
        tableForm.tableParameter.showSettingsButtons = false;
        tableForm.tableParameter.showColumnSettingsButtons = true;

        const staticObjects = new StaticObjectQuery(viewData.result);
        tableForm.callbackLoadItems = async (parameter) => {
            return staticObjects.getFilteredObject(parameter);
        };

        await tableForm.createFormByCollection(parent);
    }
}

// Created by DatenMeister.SourcecodeGenerator.TypeScriptInterfaceGenerator Version 1.3.0.0
export namespace _Root
{
    export class _ViewNodeRenderAction
    {
        static viewNode = "viewNode";
    }

    export const __ViewNodeRenderAction_Uri = "dm:///types.forms.dataview.datenmeister/#06f21d5d-3813-4810-a63c-16f12ef5d175";
    export class _ViewDataTable
    {
        static viewNode = "viewNode";
        static tableForm = "tableForm";
        static _name_ = "name";
        static title = "title";
        static isReadOnly = "isReadOnly";
        static isAutoGenerated = "isAutoGenerated";
        static hideMetaInformation = "hideMetaInformation";
        static originalUri = "originalUri";
        static originalWorkspace = "originalWorkspace";
        static creationProtocol = "creationProtocol";
    }

    export const __ViewDataTable_Uri = "dm:///types.forms.dataview.datenmeister/#0e2986e0-2982-426e-8024-71a100f1e7d0";
}

