// Created by DatenMeister.SourcecodeGenerator.TypeScriptInterfaceGenerator Version 1.3.0.0
export namespace _Root
{
        export class _ViewNodeRenderAction
        {
            static viewNode = "viewNode";
        }

        export const __ViewNodeRenderAction_Uri = "dm:///types.forms.dataview.datenmeister/#06f21d5d-3813-4810-a63c-16f12ef5d175";
        export class _ViewDataTable
        {
            static viewNode = "viewNode";
            static tableForm = "tableForm";
            static _name_ = "name";
            static title = "title";
            static isReadOnly = "isReadOnly";
            static isAutoGenerated = "isAutoGenerated";
            static hideMetaInformation = "hideMetaInformation";
            static originalUri = "originalUri";
            static originalWorkspace = "originalWorkspace";
            static creationProtocol = "creationProtocol";
        }

        export const __ViewDataTable_Uri = "dm:///types.forms.dataview.datenmeister/#0e2986e0-2982-426e-8024-71a100f1e7d0";
}

