= Issue 62 - Fast Import of Excel

== Use Case

The user shall be able to import an Excel file by just selecting the Excel File and performing some configurations.

== Requirements

* The user shall be able to start importing of an Excel just by cliking a button in the workspace overview
* The user shall be able to define out of one of the followimg actions directly via a dropdown
** Onetime import: Just adding it in an Xmi Extent
** Read-Only connection: The Excel is internally converted to an InMemory Extent and changes will be lost at next start-up
** Synchronization: The Excel is loaded, but changes are written back to Excel when writing is activated

== Design

* We keep the three instances as they contain additional information about the persistance capability and others
** [ ] Remove the Import Type... It's a pity, but nobody is using it
** [ ] The three existing ExtentLoaderConfigs are to be renamed to be more specific:
*** ExcelConvertToXmiLoader
*** ExcelReadLoader
*** ExcelFullSyncLoader
* [ ] We need to add three buttons for each type at the Workspace Detail View
** [ ] To achieve that, we need to be capable to add multiple action buttons in one row
** [ ] This means that we need to extent the Action Buttons datastructure (see below)
** [ ] This means that we need to extent the View logic (see below)
* [ ] We need to add an action which just shows the new ExtentLoader which can be filled out by the user

=== Design Multiaction-Buttons

* [ ] We will add a new datatype that allows to add multiple field in one row
** MergedFieldsInCellData
*** Attribute: fields
* [ ] We create a ActionHandler in TypeScript which renders the multiple fields into one cell

== Verification

* [ ] Create update unit test which gives evidence that all ExtentLoaderConfig import types are working property
* [ ] Perform a manual check on the website that the import is working