= Swimlanes

== Purpose and Usecase

We would like to generate a report out of a set of objects which collect the objects in a swimlane-based table view.

Using as an example:

* We have a set of tasks which are planned on a sprint and are assigned to a person.
* Out of that set of tasks, a table shall be created in which the sprints are ordered and shown as vertical swimlanes.
** The assigned person are shown as horizontal swimlanes.

As an example assuming the following data

=== Example Data

[cols="1,2,2", options="header"]
|===
| Task | Sprint | Assigned To

| Fix login bug
| Sprint 1
| Alice

| Write unit tests
| Sprint 1
| Bob

| Implement search
| Sprint 2
| Alice

| Code review
| Sprint 2
| Alice

| Deploy to staging
| Sprint 2
| Bob

| Update documentation
| Sprint 3
| Carol

| Performance tuning
| Sprint 3
| Bob

| Fix export issue
| Sprint 3
| Carol
|===

=== Resulting Swimlane Table

The sprints form the columns (vertical swimlanes) and the assigned persons form the rows (horizontal swimlanes):

[cols="1,2,2,2", options="header"]
|===
| Assigned To | Sprint 1 | Sprint 2 | Sprint 3

| Alice
| Fix login bug
| Implement search +
Code review
|

| Bob
| Write unit tests
| Deploy to staging
| Performance tuning

| Carol
|
|
| Update documentation +
Fix export issue
|===

== Requirements

* The swimlane table shall support a vertical and horizontal swimlane, each by a configurable property
* The swimlane can be shown in the webview by clicking on a Swimlane-Table-Configuration
* The Object and Collection view shall support a tab of a Swimlane Table as a configurable plugin. 
* The swimlane table shall exportable as a file (html)
** The rendering of the swimlane shall happen in JavaScript to support offline export
* The clustering of data in swimlane rows and columns shall be supported as a datatransformation, so other tools can
directly work on the transformed data.

== Design

* An own assembly with data types and Javascript files will be implemented
* The extent url will be "dm:///intern.types.swimlane.datenmeister/"
** We need to have a template for that procedure. 

The following tasks: 

* [x] Create new Assembly: DatenMeister.Reports.Swimlane
* [x] Add project configuration for Extent for types
* [x] Add project configuration for Typescript conversion

=== Configuration

The Swimlane configuration describes of how to create the swimlane table. It does not contain the reference to the 
data itself, it just describes how the swimlane table shall be generated out of objects which are 'filled-in'.

The configuration data will be the following:

*SwimlaneConfiguration*

[cols="1,3", options="header"]
|===
|Property|Meaning
|verticalSwimlaneProperty|Name of the property which will be spanned up in vertical swimlanes. As in the example
above, it is the "Sprint".
|horizontalSwimlaneProperty|Name of the property which will be spanned up in vertical swimlanes. As in the example
above, it is the "Assigned To"
|cellContent|Scriban template which will be used to show the content. In case the value is not set, the standard
Name will be used
|linkContent|Boolean indicating whether a link shall be added.
|===

* [x] Create the metaclass for the configuration

=== The viewdefinition

The Swimlane view definition contains the specific view information which allows the rendering of the
swimlane. It contains the information about the view definition and how to retrieve the items.

*SwimlaneViewdefinition*

[cols="1,3", options="header"]
|===
|Property|Meaning
|swimlaneConfiguration|Reference to the swimlane configuration
|viewNode|Composite of the viewNode which retrieves all the items that are intended to get rendered.
|===

* [x] Create the view definition metaclass

The viewdefinition will call a specific action to render the swimlane upon a click on the button.

The corresponding action will be called 'SwimlaneRenderAction' and will create the new page upon click. The action is
just performed on the client by directly returning the Client Action to open the new window. 

The same action under context of 'render' returns again a ClientAction which triggers the formlogic and performs
the rendering of the page itself

* [ ] Realize Action Logic for 'SwimlaneRenderAction'
* [ ] Add context to IActionHandler implementation
* [ ] Create Clientaction which opens a new window with a specific url

* [ ] Create new Master Page just loading the action in a specific context
* [ ] Realize clientaction to render a form

An action button starting all the actions above is added to the default form of the Viewdefinition 

* [ ] Include an action button for metaclass of 'SwimlaneRenderAction'
** [ ] Here, we render 

=== Create the action to show the viewdefinition

The item view of the view definition needs to include a button which just shows the swimlane as a seperate page.
The page contains the client scripting which dynamically reads in the transformed data and renders it on the screen 
itself. 

Currently, the DatenMeister does not allow to create a dedicated page, just showing the contants of a view. This means,
we need to develop a special page which just shows the control.

* [ ] Load the view definition and corresponding swimlane configuration
* [ ] Requests the transformed data from the server.
** [ ] Create a special viewNode which transforms the data according the configuration on the server
** [ ] The Javascript logic needs to create a query by loading the referenced View Defintion appended by the
swimlane transformation
* [ ] Rendering the table. 
** [ ] This rendering shall be decoupled from the dynamic loading, so a static view could also be generated by 
an offline page which has the data incorporated as a javascript





