= Swimlanes

== Purpose and Usecase

We would like to generate a report out of a set of objects which collect the objects in a swimlane-based table view.

Using as an example:

* We have a set of tasks which are planned on a sprint and are assigned to a person.
* Out of that set of tasks, a table shall be created in which the sprints are ordered and shown as vertical swimlanes.
** The assigned person are shown as horizontal swimlanes.

As an example assuming the following data

=== Example Data

[cols="1,2,2", options="header"]
|===
| Task | Sprint | Assigned To

| Fix login bug
| Sprint 1
| Alice

| Write unit tests
| Sprint 1
| Bob

| Implement search
| Sprint 2
| Alice

| Code review
| Sprint 2
| Alice

| Deploy to staging
| Sprint 2
| Bob

| Update documentation
| Sprint 3
| Carol

| Performance tuning
| Sprint 3
| Bob

| Fix export issue
| Sprint 3
| Carol
|===

=== Resulting Swimlane Table

The sprints form the columns (vertical swimlanes) and the assigned persons form the rows (horizontal swimlanes):

[cols="1,2,2,2", options="header"]
|===
| Assigned To | Sprint 1 | Sprint 2 | Sprint 3

| Alice
| Fix login bug
| Implement search +
Code review
|

| Bob
| Write unit tests
| Deploy to staging
| Performance tuning

| Carol
|
|
| Update documentation +
Fix export issue
|===

== Requirements

* The swimlane table shall support a vertical and horizontal swimlane, each by a configurable property
* The swimlane can be shown in the webview by clicking on a Swimlane-Table-Configuration
* The Object and Collection view shall support a tab of a Swimlane Table as a configurable plugin. 
* The swimlane table shall exportable as a file (html)
** The rendering of the swimlane shall happen in JavaScript to support offline export
* The clustering of data in swimlane rows and columns shall be supported as a datatransformation, so other tools can
directly work on the transformed data.

== Design

* An own assembly with data types and Javascript files will be implemented
* The extent url will be "dm:///intern.types.swimlane.datenmeister/"
** We need to have a template for that procedure. 

The following tasks: 

* [x] Create new Assembly: DatenMeister.Reports.Swimlane
* [x] Add project configuration for Extent for types
* [x] Add project configuration for Typescript conversion

=== Configuration

The Swimlane configuration describes of how to create the swimlane table. It does not contain the reference to the 
data itself, it just describes how the swimlane table shall be generated out of objects which are 'filled-in'.

The configuration data will be the following:

*SwimlaneConfiguration*

[cols="1,3", options="header"]
|===
|Property|Meaning
|verticalSwimlaneProperty|Name of the property which will be spanned up in vertical swimlanes. As in the example
above, it is the "Sprint".
|horizontalSwimlaneProperty|Name of the property which will be spanned up in vertical swimlanes. As in the example
above, it is the "Assigned To"
|cellContent|Scriban template which will be used to show the content. In case the value is not set, the standard
Name will be used
|linkContent|Boolean indicating whether a link shall be added.
|===

* [x] Create the metaclass for the configuration

=== The viewdefinition

The Swimlane view definition contains the specific view information which allows the rendering of the
swimlane. It contains the information about the view definition and how to retrieve the items.

*SwimlaneViewdefinition*

[cols="1,3", options="header"]
|===
|Property|Meaning
|swimlaneConfiguration|Reference to the swimlane configuration
|viewNode|Composite of the viewNode which retrieves all the items that are intended to get rendered.
|===

The viewdefinition will become inherited by an Action which will allow the direct triggering of an actionhandler.

* [x] Create the view definition metaclass
* [x] Inherit from ActionHandler

The viewdefinition will call a specific action to render the swimlane upon a click on the button.

The corresponding action will be called 'SwimlaneRenderAction' and will create the new page upon click. The action is
just performed on the client by directly returning the Client Action to open the new window. 

The new page is a simple page which takes a url of an action. The action is then executed on the server and the
returned ClientActions are evaluated by the FormActions.ts. The page is called 'ActionPure'. It contains the 
necessary TypeScript logic in the Page/ActionPure.ts and a simple div (name: pageContent) which can be used by the
client actions to render the result. 

The same action under context of 'render' returns again a ClientAction which triggers the formlogic and performs
the rendering of the page itself.

* [x] Create Clientaction which opens a new window with a specific url
* [x] Create ClientAction which opens the new Master Page triggering the context. 

* [x] Create new Master Page just loading the action in a specific context
* [x] Realize clientaction to render a form, the form should be directly returned via the post query. 

An action button starting all the actions above is added to the default form of the Viewdefinition 

* [x] Include an action button for metaclass of 'SwimlaneRenderAction'

=== Create an action which shows the result of a Viewnode

We would like to have a button on all detail forms of the specializations of the ViewNode. 
By clicking on that button, the popup shall be opened and all selected items is to be shown. 

This is done by the following steps: 

* [x] Add the button upon ViewNode, here a new assembly will be created called 'DatenMeister.DataView.Forms'.
** [x] Here, we probably need to add a simple check whether the instance's type is generalized to a ViewNode.

To actively render the found items, a temporary action is created which requests the rendering of the form.
This is managed via the client as a Client Action via 'DatenMeister.ViewNodes.RenderItemsInPopup'.

* [ ] Define class of the ViewNodeRenderAction 
* [ ] Create temporary element upon click.
* [ ] Navigate ActionPure to that element.

=== Create the action to show the viewdefinition

The item view of the view definition needs to include a button which just shows the swimlane as a separate page.

* [x] Include a button to request the action as a popup

It shall open the page and request the action execution with actionverb 'render'. As a return, a dedicated form is returned which includes the form to show the swimlane as an item form. 

The item form loads the viewnode and context and requests also the transformation on the server. Here, a special viewnode will be generated which just takes the SwimlangeViewDefinition and returns an enumeration of items in row and columns.

* [ ] Create the action handler which returns a form. It shall just react upon actionVerb="Render"
** [ ] Update the action handler chain to manage the actionVerb
* [ ] Create clientform class definition (SwimlaneForm) for the swimlane
** [ ] Data (reference to SwimlaneViewDefinition)
** [ ] Register in JavaScript just to return a dummy element
* [ ] Update the action handler that the SwimlaneView is return
* [ ] Implement special viewnode for SwimlaneTransformation
* [ ] Add Javascript that the viewnode is called and data is returned
* [ ] Render the table itself
