using System;
using System.Collections.Generic;
using System.Linq;
using DatenMeister.Core.EMOF.Interface.Common;
using DatenMeister.Core.EMOF.Interface.Reflection;
using DatenMeister.Core.Helper;
using DatenMeister.Core.Models;
using DatenMeister.Core.Models.EMOF;
using DatenMeister.Core.Runtime;
using DatenMeister.Core.Uml.Helper;

namespace DatenMeister.Forms.FormCreator
{
    public partial class FormCreator
    {
        /// <summary>
        ///     Creates the list form out of the elements in the reflective collection.
        ///     Supports the creation by the metaclass and by the object's properties
        /// </summary>
        /// <param name="elements">Elements to be queried</param>
        /// <param name="creationMode">The used creation mode</param>
        /// <returns>The created list form </returns>
        public IElement CreateTableFormForCollection(
            IReflectiveCollection elements,
            FormFactoryConfiguration creationMode)
        {
            var result = GetMofFactory(creationMode).create(_DatenMeister.TheOne.Forms.__TableForm);
            result.set(_DatenMeister._Forms._TableForm.isAutoGenerated, true);
            
            AddToTableFormByElements(result, elements, creationMode with { IsForTableForm = true });

            CleanUpTableForm(result);
            
            return result;
        }

        /// <summary>
        ///     Creates a list form for a certain metaclass being used inside an extent form
        /// </summary>
        /// <param name="element">Element being used to determine the propertytype... But this is empty</param>
        /// <param name="propertyName">Name of the property</param>
        /// <param name="propertyType"></param>
        /// <param name="creationMode"></param>
        public IElement CreateTableFormForProperty(
            IObject? element,
            string propertyName,
            IElement? propertyType,
            FormFactoryConfiguration creationMode)
        {
            if (!creationMode.CreateByMetaClass)
                throw new InvalidOperationException("The list form will only be created for the metaclass");

            var tableFormForPropertyValues = GetMofFactory(creationMode).create(_DatenMeister.TheOne.Forms.__TableForm);
            tableFormForPropertyValues.set(_DatenMeister._Forms._TableForm.isAutoGenerated, true);

            FormMethods.AddToFormCreationProtocol(
                tableFormForPropertyValues,
                "[FormCreator.CreateTableFormForProperty]");

            AddFieldsToRowOrTableFormByMetaClass(tableFormForPropertyValues, propertyType, creationMode);
            tableFormForPropertyValues.set(_DatenMeister._Forms._TableForm.property, propertyName);
            tableFormForPropertyValues.set(_DatenMeister._Forms._TableForm.metaClass, propertyType);
            tableFormForPropertyValues.set(_DatenMeister._Forms._TableForm.title,
                $"{propertyName} - {NamedElementMethods.GetName(propertyType)}");
            if (propertyType != null)
            {
                FormMethods.AddDefaultTypeForNewElement(tableFormForPropertyValues, propertyType);
            }

            FormMethods.AddToFormCreationProtocol(
                tableFormForPropertyValues,
                "[FormCreator.CreateTableFormForProperty] Set default type: " +
                NamedElementMethods.GetName(propertyType));

            CleanUpTableForm(tableFormForPropertyValues);
            
            return tableFormForPropertyValues;
        }

        /// <summary>
        ///     Creates a list form for a certain metaclass
        /// </summary>
        /// <param name="metaClass"></param>
        /// <param name="creationMode"></param>
        public IElement CreateTableFormForMetaClass(
            IElement? metaClass,
            FormFactoryConfiguration creationMode)
        {
            return CreateTableFormForMetaClass(metaClass, creationMode, null);
        }

        /// <summary>
        ///     Creates a list form for a certain metaclass
        /// </summary>
        /// <param name="metaClass"></param>
        /// <param name="creationMode"></param>
        /// <param name="property">Property being used</param>
        public IElement CreateTableFormForMetaClass(
            IObject? metaClass,
            FormFactoryConfiguration creationMode,
            IElement? property = null)
        {
            if (!creationMode.CreateByMetaClass)
                throw new InvalidOperationException("The list form will only be created for the metaclass");

            var form = GetMofFactory(creationMode).create(_DatenMeister.TheOne.Forms.__TableForm);
            var realPropertyName = NamedElementMethods.GetName(property);
            var propertyName = property != null ? realPropertyName : "";
            form.set(_DatenMeister._Forms._TableForm.isAutoGenerated, true);

            FormMethods.AddToFormCreationProtocol(
                form,
                "[FormCreator.CreateTableFormForMetaClass] Created for: " + NamedElementMethods.GetName(metaClass));

            var title =
                (metaClass != null ? "'" + NamedElementMethods.GetName(metaClass) + "'" : string.Empty) +
                (metaClass != null && !string.IsNullOrEmpty(propertyName) ? " - " : "") +
                propertyName;

            form.set(_DatenMeister._Forms._TableForm.title, "Items of type " + title);
            form.set(_DatenMeister._Forms._TableForm.name, title);
            if (property != null)
            {
                form.set(_DatenMeister._Forms._TableForm.property, realPropertyName);
            }

            if (metaClass != null)
            {
                AddFieldsToRowOrTableFormByMetaClass(form, metaClass, creationMode with { IsForTableForm = true });
                
                FormMethods.AddToFormCreationProtocol(
                    form,
                    "[FormCreator.CreateTableFormForMetaClass] Added Default Type for: " +
                    NamedElementMethods.GetName(metaClass));

                FormMethods.AddDefaultTypeForNewElement(form, metaClass);
            }
            else
            {
                // Ok, we have no metaclass, but let's add at least the columns for the property 'name'
                AddFieldsToFormByMetaClassProperty(
                    form,
                    _UML.TheOne.CommonStructure.NamedElement._name,
                    new FormFactoryConfiguration
                        { CreateByPropertyValues = false, AutomaticMetaClassField = false, IsForTableForm = true },
                    FormUmlElementType.Property);
            }

            CleanUpTableForm(form);
            
            return form;
        }

        /// <summary>
        ///     Adds the property to the list elements by parsing through the
        /// </summary>
        /// <param name="form">Contains the form which is parsed</param>
        /// <param name="elements">Goes through the elements</param>
        /// <param name="creationMode">The creation mode to be used</param>
        public void AddToTableFormByElements(
            IElement form,
            IReflectiveCollection elements,
            FormFactoryConfiguration creationMode)
        {
            var metaClassAdded = false;
            var onlyCommonProperties = creationMode.IncludeOnlyCommonProperties;

            var cache = new FormCreatorCache();
            var alreadyVisitedMetaClasses = new HashSet<IElement>();

            IObject? firstElementMetaClass = null;

            // Figure out only the elements which have common properties
            var propertyNames = onlyCommonProperties ? new HashSet<string>() : null;

            if (propertyNames != null)
            {
                SelectOnlyCommonPropertyNames(elements, propertyNames, creationMode);

                foreach (var propertyName in propertyNames) cache.FocusOnPropertyNames.Add(propertyName);
            }

            foreach (var element in elements.OfType<IObject>())
            {
                var metaClass = (element as IElement)?.getMetaClass();
                if (firstElementMetaClass == null || !creationMode.AutomaticMetaClassField)
                {
                    // If this is the first element or when the reportCreator does not allow the addition
                    // of a metaclass
                    firstElementMetaClass = metaClass;
                }
                else if (!Equals(firstElementMetaClass, metaClass)
                         && !metaClassAdded
                         && !cache.MetaClassAlreadyAdded
                         && creationMode.AutomaticMetaClassField
                         && !FormMethods.HasMetaClassFieldInForm(form))
                {
                    metaClassAdded = true;
                    cache.MetaClassAlreadyAdded = true;

                    // Create the metaclass as a field
                    var metaClassField = GetMofFactory(creationMode).create(_DatenMeister.TheOne.Forms.__MetaClassElementFieldData);
                    metaClassField.set(_DatenMeister._Forms._MetaClassElementFieldData.name, "Metaclass");
                    metaClassField.set(_DatenMeister._Forms._MetaClassElementFieldData.title, "Metaclass");
                    form.get<IReflectiveSequence>(_DatenMeister._Forms._TableForm.field).add(0, metaClassField);

                    FormMethods.AddToFormCreationProtocol(
                        form,
                        "[FormCreator.AddToTableFormByElements] Added metaclass");
                }

                if (creationMode.CreateByMetaClass && metaClass != null)
                {
                    if (alreadyVisitedMetaClasses.Contains(metaClass)) continue;

                    alreadyVisitedMetaClasses.Add(metaClass);
                    AddFieldsToRowOrTableFormByMetaClass(form, metaClass, creationMode with { IsForTableForm = true }, cache);
                }
                else if (creationMode.CreateByPropertyValues)
                {
                    AddFieldsToForm(
                        form,
                        element,
                        creationMode with { CreateByMetaClass = false, IsForTableForm = true },
                        cache);
                }

            }
        }

        /// <summary>
        ///     Defines the property names to be used when the creation flag contains 'OnlyCommon' Properties
        /// </summary>
        /// <param name="elements">The enumeration of elements which are parsed</param>
        /// <param name="propertyNames">A set of property names which are evaluated. The set is also modified</param>
        /// <param name="creationMode">The creation mode to be used</param>
        private void SelectOnlyCommonPropertyNames(
            IReflectiveCollection elements,
            ISet<string> propertyNames,
            FormFactoryConfiguration creationMode)
        {
            if (elements == null) throw new ArgumentNullException(nameof(elements));
            if (propertyNames == null) throw new ArgumentNullException(nameof(propertyNames));

            var firstRun = true;
            var toBeDeleted = new HashSet<string>();

            // Parses the meta class
            if (creationMode.CreateByMetaClass)
                foreach (var element in elements.OfType<IElement>())
                {
                    var metaClass = element.getMetaClass();
                    if (metaClass == null) continue;

                    var propertiesOfElement =
                        ClassifierMethods.GetPropertyNamesOfClassifier(metaClass)
                            .ToList();

                    ThinOutPropertyNames(propertiesOfElement, element);
                    firstRun = false;
                }

            // Parses the property values
            if (creationMode.CreateByPropertyValues)
                foreach (var element in elements.OfType<IElement>())
                {
                    var hasProperties = element as IObjectAllProperties;
                    if (hasProperties == null) continue;

                    var propertiesOfElement = hasProperties.getPropertiesBeingSet().ToList();

                    ThinOutPropertyNames(propertiesOfElement, element);
                    firstRun = false;
                }

            void ThinOutPropertyNames(ICollection<string> propertiesOfElement, IElement element)
            {
                // Add the properties into the list, if first run or safe property
                foreach (var propertyName in propertiesOfElement)
                {
                    if (firstRun)
                    {
                        propertyNames.Add(propertyName);
                    }
                    else
                    {
                        var isSafeProperty = DefaultClassifierHints.IsGenericProperty(element, propertyName);
                        if (isSafeProperty) propertyNames.Add(propertyName);
                    }
                }

                // Check which properties are in the list but not in the object
                toBeDeleted.Clear();
                foreach (var propertyName in propertyNames)
                {
                    var isSafeProperty = DefaultClassifierHints.IsGenericProperty(element, propertyName);
                    if (!propertiesOfElement.Contains(propertyName) && !isSafeProperty) toBeDeleted.Add(propertyName);
                }

                // Now perform the deletion
                foreach (var propertyName in toBeDeleted) propertyNames.Remove(propertyName);
            }
        }

        /// <summary>
        ///     Creates a list form for a certain metaclass being used inside an extent form
        /// </summary>
        /// <param name="property">Property to be evaluated</param>
        /// <param name="creationMode"></param>
        public IElement CreateTableFormForProperty(IElement property, FormFactoryConfiguration creationMode)
        {
            if (!creationMode.CreateByMetaClass)
                throw new InvalidOperationException("The list form will only be created for the metaclass");

            var propertyName = property.getOrDefault<string>(_UML._CommonStructure._NamedElement.name);
            var propertyType = PropertyMethods.GetPropertyType(property);

            var result = GetMofFactory(creationMode).create(_DatenMeister.TheOne.Forms.__TableForm);

            FormMethods.AddToFormCreationProtocol(
                result,
                "[FormCreator.CreateTableFormForProperty] Created for Property: " + propertyName);

            if (propertyType != null) AddFieldsToRowOrTableFormByMetaClass(result, propertyType, creationMode);
            result.set(_DatenMeister._Forms._TableForm.property, propertyName);
            result.set(_DatenMeister._Forms._TableForm.title, $"{propertyName}");
            result.set(_DatenMeister._Forms._TableForm.isAutoGenerated, true);

            CleanUpTableForm(result);
            return result;
        }

        public void CleanUpTableForm(IElement listForm)
        {
            AddTextFieldForNameIfNoFieldAvailable(listForm);
            SortFieldsByImportantProperties(listForm);
        }
    }
}