<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DatenMeister.Plugins.Helper\DatenMeister.Plugins.Helper.csproj" />
      <ProjectReference Include="..\..\src\DatenMeister.Plugins\DatenMeister.Plugins.csproj" />
      <ProjectReference Include="..\..\src\Web\DatenMeister.WebServer.Library\DatenMeister.WebServer.Library.csproj" />
    </ItemGroup>

    <ItemGroup>
      <TypeScriptConfigFile Include="tsconfig.json" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Js\Demo.js" />
      <EmbeddedResource Include="Js\Demo.js" />
      <None Remove="Xmi\Types.xmi" />
      <EmbeddedResource Include="Xmi\Types.xmi" />
    </ItemGroup>

    <Target Name="RunCakeBuild" BeforeTargets="Build">
        <Exec Command="npm install" />
        <Exec Command="dotnet tool install Cake.Tool --version 6.1.0" />
        <Exec Command="dotnet cake build.cake --target=Build" />
    </Target>

</Project>
