using DatenMeister.Core.Interfaces;
using DatenMeister.Core.Interfaces.MOF.Reflection;

// ReSharper disable InconsistentNaming
// ReSharper disable RedundantNameQualifier
// Created by DatenMeister.SourcecodeGenerator.ClassTreeGenerator Version 1.3.0.0
namespace DatenMeister.DataView.Forms.Model;

public class _Root
{
    [TypeUri(Uri = "dm:///types.forms.dataview.datenmeister/#06f21d5d-3813-4810-a63c-16f12ef5d175",
        TypeKind = TypeKind.ClassTree)]
    public class _ViewNodeRenderAction
    {
        public static readonly string @viewNode = "viewNode";
        public IElement? @_viewNode = null;

    }

    public _ViewNodeRenderAction @ViewNodeRenderAction = new ();
    public MofObjectShadow @__ViewNodeRenderAction = new ("dm:///types.forms.dataview.datenmeister/#06f21d5d-3813-4810-a63c-16f12ef5d175");

    [TypeUri(Uri = "dm:///types.forms.dataview.datenmeister/#0e2986e0-2982-426e-8024-71a100f1e7d0",
        TypeKind = TypeKind.ClassTree)]
    public class _ViewDataTable
    {
        public static readonly string @viewNode = "viewNode";
        public IElement? @_viewNode = null;

        public static readonly string @tableForm = "tableForm";
        public IElement? @_tableForm = null;

        public static readonly string @name = "name";
        public IElement? @_name = null;

        public static readonly string @title = "title";
        public IElement? @_title = null;

        public static readonly string @isReadOnly = "isReadOnly";
        public IElement? @_isReadOnly = null;

        public static readonly string @isAutoGenerated = "isAutoGenerated";
        public IElement? @_isAutoGenerated = null;

        public static readonly string @hideMetaInformation = "hideMetaInformation";
        public IElement? @_hideMetaInformation = null;

        public static readonly string @originalUri = "originalUri";
        public IElement? @_originalUri = null;

        public static readonly string @originalWorkspace = "originalWorkspace";
        public IElement? @_originalWorkspace = null;

        public static readonly string @creationProtocol = "creationProtocol";
        public IElement? @_creationProtocol = null;

    }

    public _ViewDataTable @ViewDataTable = new ();
    public MofObjectShadow @__ViewDataTable = new ("dm:///types.forms.dataview.datenmeister/#0e2986e0-2982-426e-8024-71a100f1e7d0");

    public static readonly _Root TheOne = new ();

}

