//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatenMeister.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatenMeisterTestsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatenMeisterTestsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatenMeister.Tests.DatenMeisterTestsResources", typeof(DatenMeisterTestsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;m&quot;:{
        ///      &quot;uri&quot;:&quot;dm:///_internal/types/internal#b8333b8d-ac49-4a4e-a7f4-c3745e0a0237&quot;,
        ///      &quot;workspace&quot;:&quot;Types&quot;
        ///   },
        ///   &quot;id&quot;:&quot;local_169&quot;,
        ///   &quot;v&quot;:{
        ///      &quot;_AddQueryInPackageAction&quot;:[
        ///         true,
        ///         &quot;test&quot;
        ///      ],
        ///      &quot;targetPackageUri&quot;:[
        ///         true,
        ///         &quot;dm:///_internal/forms/user&quot;
        ///      ],
        ///      &quot;targetPackageWorkspace&quot;:[
        ///         true,
        ///         &quot;Management&quot;
        ///      ],
        ///      &quot;query&quot;:[
        ///         true,
        ///         {
        ///            &quot;m&quot;:{
        ///               &quot;uri&quot;:&quot;dm:///_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MofJsonTests_TestQueryObjectExample {
            get {
                return ResourceManager.GetString("MofJsonTests_TestQueryObjectExample", resourceCulture);
            }
        }
    }
}
