<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DatenMeister.Actions\DatenMeister.Actions.csproj" />
      <ProjectReference Include="..\..\DatenMeister.Plugins.Helper\DatenMeister.Plugins.Helper.csproj" />
      <ProjectReference Include="..\..\DatenMeister.Plugins\DatenMeister.Plugins.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Assets\Js\" />
      <Folder Include="Xmi\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Xmi\Types.xmi" />
      <EmbeddedResource Include="Xmi\Types.xmi" />
      <None Include=".bsmake\Build.cs" />
      <None Remove="Assets\Css\datenmeister-web.min.css" />
      <EmbeddedResource Include="Assets\Css\datenmeister-web.min.css" />
        <None Remove="Assets\Css\bootstrap.min.css" />
        <EmbeddedResource Include="Assets\Css\bootstrap.min.css" />
      <None Remove="Assets\Js-Bundled\index.js" />
      <EmbeddedResource Include="Assets\Js-Bundled\index.js" />
      <None Remove="Assets\Js-Bundled\jquery.min.js" />
      <EmbeddedResource Include="Assets\Js-Bundled\jquery.min.js" />
    </ItemGroup>

    <ItemGroup>
      <Content Include=".bsmake\Build.csproj" />
    </ItemGroup>

    <ItemGroup>
      <TypeScriptConfigFile Include="tsconfig.json" />
    </ItemGroup>

</Project>
