using DatenMeister.Core.EMOF.Interface.Reflection;
using DatenMeister.Core.Models;
using DatenMeister.Core.Uml.Helper;
using DatenMeister.Forms.FormFactory;

namespace DatenMeister.Forms.CollectionForms;

public class CollectionFormFromMetaClass : ICollectionFormFactory
{
    public void CreateCollectionForm(CollectionFormFactoryParameter parameter, FormCreationContext context,
        FormCreationResultOneForm result)
    {
        if (parameter.MetaClass == null)
            return;

        var metaClass = parameter.MetaClass;

        result.Form ??= context.Global.Factory.create(_Forms.TheOne.__CollectionForm);
        result.Form.set(_Forms._ObjectForm.name, $"ListForm for '{NamedElementMethods.GetName(metaClass)}'");
        result.Form.set(_Forms._ObjectForm.isAutoGenerated, true);

        result.AddToFormCreationProtocol(
            "[CollectionFormFromData.CreateCollectionFormForItemsMetaClass]: Add Extent by Metaclass: " +
            NamedElementMethods.GetName(metaClass));

        var tabs = new List<IElement>();

        // Get all properties of the elements
        var properties = ClassifierMethods.GetPropertiesOfClassifier(metaClass).ToList();
        if (properties == null)
            throw new InvalidOperationException(
                "CollectionForm cannot be created because given element does not have properties");

        var propertiesWithCollection =
            (from p in properties
                where PropertyMethods.IsCollection(p)
                select new { propertyName = NamedElementMethods.GetName(p), property = p }).ToList();

        var propertiesWithoutCollection =
            (from p in properties
                where !PropertyMethods.IsCollection(p)
                select new { propertyName = NamedElementMethods.GetName(p), property = p }).ToList();

        if (propertiesWithoutCollection.Any())
        {
            var innerContext = context.Clone();
            var rowForms = FormCreation.CreateRowForm(
                new RowFormFactoryParameter
                {
                    MetaClass = parameter.MetaClass,
                    Extent = parameter.Extent,
                    ExtentTypes = parameter.ExtentTypes
                },
                innerContext
            ).Forms;

            foreach (var rowForm in rowForms)
            {
                rowForm.set(_Forms._RowForm.name, "Detail");
                result.AddToFormCreationProtocol(
                    "[FormCreator.CreateCollectionFormForItemsMetaClass]: Add DetailForm");

                tabs.Add(rowForm);
            }
        }

        foreach (var pair in propertiesWithCollection)
        {
            result.AddToFormCreationProtocol(
                "[CollectionFormFromData.CreateCollectionFormForItemsMetaClass]: Add ListForm: " +
                NamedElementMethods.GetName(pair.property));

            var propertyType = PropertyMethods.GetPropertyType(pair.property);
            if (propertyType != null)
            {
                // Now try to figure out the metaclass

                foreach (var tableForm in FormCreation.CreateTableForm(
                             new TableFormFactoryParameter
                             {
                                 MetaClass = propertyType
                             }, context.Clone()).Forms)
                {
                    tableForm.set(
                        _Forms._TableForm.title,
                        "Property: packagedElements of type " + NamedElementMethods.GetName(propertyType));

                    tabs.Add(tableForm);
                }
            }
        }

        result.Form.set(_Forms._CollectionForm.tab, tabs);
        result.IsManaged = result.IsMainContentCreated = true;

    }
}