using DatenMeister.Core.EMOF.Interface.Common;
using DatenMeister.Core.Models;
using DatenMeister.Forms.FormFactory;

namespace DatenMeister.Forms.CollectionForms;

/// <summary>
/// The factory which creates an empty collection form. 
/// </summary>
public class EmptyCollectionFormFactory : INewCollectionFormFactory
{
    public void CreateCollectionFormForCollection(
        IReflectiveCollection collection,
        NewFormCreationContext context,
        FormCreationResult result)
    {
        var collectionForm = context.Global.Factory.create(_Forms.TheOne.__CollectionForm);
        collectionForm.set(_Forms._ObjectForm.isAutoGenerated, true);

        result.Result = collectionForm;
        result.IsManaged = true;
        
        result.AddToFormCreationProtocol(
            "[EmptyCollectionFormFactory] Empty object Collection-Form created");
    }
}