// Created by DatenMeister.SourcecodeGenerator.TypeScriptInterfaceGenerator Version 1.0.0.0
export var _Root;
(function (_Root) {
    class _ReportFieldData {
    }
    _ReportFieldData._name_ = "name";
    _ReportFieldData.title = "title";
    _ReportFieldData.isReadOnly = "isReadOnly";
    _ReportFieldData.isAutoGenerated = "isAutoGenerated";
    _ReportFieldData.hideMetaInformation = "hideMetaInformation";
    _ReportFieldData.originalUri = "originalUri";
    _ReportFieldData.creationProtocol = "creationProtocol";
    _Root._ReportFieldData = _ReportFieldData;
    _Root.__ReportFieldData_Uri = "dm:///types/#89dea433-d199-4889-95eb-7ef30c0b5695";
})(_Root || (_Root = {}));
//# sourceMappingURL=DatenMeister.Reports.Types.js.map