// Created by DatenMeister.SourcecodeGenerator.TypeScriptInterfaceGenerator Version 1.0.0.0
export var _Root;
(function (_Root) {
    class _ReportForm {
    }
    _ReportForm._name_ = "name";
    _ReportForm.title = "title";
    _ReportForm.isReadOnly = "isReadOnly";
    _ReportForm.isAutoGenerated = "isAutoGenerated";
    _ReportForm.hideMetaInformation = "hideMetaInformation";
    _ReportForm.originalUri = "originalUri";
    _ReportForm.creationProtocol = "creationProtocol";
    _Root._ReportForm = _ReportForm;
    _Root.__ReportForm_Uri = "dm:///types/#89dea433-d199-4889-95eb-7ef30c0b5695";
})(_Root || (_Root = {}));
//# sourceMappingURL=DatenMeister.Reports.Types.js.map