=== Report Generator ===

A report is an automatically created document which is based upon a report definition and the stored data within the DatenMeister. 

A report definition is independent of the used data queries. 

- Report: The created document based upon a report definition and the actual data
- Report Definition: A definition describing the style, content and chapters of the report. The report definition is used by the report generator to create the report by querying the data. 
- Report Instance: A set of the Report Definition and the used queries for the creation of the report. The Report Instance is a different object compared to the Report Definition to allow multiple uses of the same Report Definition for different aspects of data. 

==== Report Definition ====

The report definition can be defined at any location within the DatenMeister. 

The definition is of type __DatenMeister.Reports.ReportDefinition__. 

The report definition contains the following fields: 

|===
|Fieldname |Purpose

|name
|Name of the report

|Title
|Title of the report

|elements
|The different elements which are combined to create the complete report
|===

A report definition contains of several elements which are appended upon each other in the final report. 

The following elements are supported and the corresponding types are residing within “DatenMeister.Reports.ReportDefinition”.

|===
|Element|Description

|headline
|Headline of the report

|paragraph
|A paragraph being included as text
|===
