=== Assemblies and Packages

==== DatenMeister.dll

This assembly contains all platform-independent functions for the DatenMeister. If an additional function needs to be included, it will be most likely be present in the DatenMeister.dll.

===== Core
Implements and defines the EMOF specification upon the Provider as being given in the Provider Package. 

===== Core.EMOF.Implementation
Contains the implementation of the EMOF specification. It relies upon the ProviderObjects. Additionally, some .Net-Helper for Type conversion and Type Lookup within extents are included here. 

===== Core.EMOF.Interfaces
Defines the interfaces as specified in the UML specification.

===== DotNet
Within this package simple helpers are implemented regarding simplification of the .Net Framework. No EMOF specific implementation can be found in this package. 

===== Integration
Allows the creation of a complete DatenMeister Scope and integrates all the different plugins of DatenMeister for easy handling. 
Especially, the ‘GiveMe’-class offers a 1-Call instantiation of the complete DatenMeister scope. 

===== Models
The models contain the .Net Types which are converted to UML classes at start-up of DatenMeister. Instead of defining the UML class in Xmi, the DotNetConverter is used to create the corresponding Uml classes.  

All other models from the different modules are also hosted within subpackages of the models. This shortens the length of the model definition. 

The models of the various Modules and Plugins are also integrated into this module. This shortens the length of the package name, so the models are within the "DatenMeister::Models::Plugin" namespace and not within "DatenMeister::Modules::Plugin::Model".  

===== Modules
This namespace includes additional function and plugins which could be hosted in a separated assembly. Each of them extend the function of DatenMeister in a certain area. 

===== Modules.DefaultTypes 
The “Modules.DefaultTypes” namespace contains several methods and function which are used in context of Uml and other MetaObjects. The namespace is used for example to add an element to a child while the model helper tries to figure out to which property the child shall be added. 

===== Provider
The “Provider” namespace include several provider which can be consumed by the Core namespace. They define the IProvider and IProviderObject interfaces which are converted to a Mof-Element. 

===== Runtime
The “Runtime” namespace include the necessary methods to bring DatenMeister into a useable product. It combines the namespace “Core” and “Provider” and offers the loader for extents, copying methods and base functions to work upon the extents, reflective sequences and objects.

===== SourcecodeGenerator
The “SourcecodeGenerator” is able to convert MOF instanciations of UML classes and MOF properties into source code that can be embedded into .Net assemblies. 

===== Uml
The “Uml” namespace include the methods to work upon Uml objects. They contain the helper methods for each class but also the plugin which defines the views for Uml objects

===== XmiFiles
This namespace just contains the Xmi-Files which are embedded into DatenMeister. For example the MOF, UML and PrimitiveType files but also additional ones which are used by the plugins. 
