== Form Manager

=== Change Form Definition

Opens the location dialog and let you choose a new form for the shown element. 

=== Reset Form Definition

=== Set as default for Metaclass

=== Clear default Association


=== Form Manager Detail Window

==== Add Property to Form...

* You open a form to which new fields shall be added in the detail window 

* By clicking upon *Create Field by Property*..., an option which is only provided, when a form is open, 

** when the form is a detail form, the elements will be directly added to the detail form. 

** when the form is a list form, the elements will be directly added to the list form. 

** when the form is an extent form, 

*** if the property corresponds to a collection, a list form will be added for this

*** if the property does not correspond to a collection, the included detail form will be enriched by the field matching to the property. If the detail form does not exist, then a new detail form will be created.

* you can select which class, property or enumeration is used as a base to automatically create a field within the opened field. 

** if the selected item is a *property*, the field is directly added into the form. Independent whether a field named like the selected property is already existing

** if the selected item is a *class*, all properties of the given item are added to the form. Independent whether a matching field is already existing

** if the selected item is an *enumeration*, a field is created with the lowercase name of the enumeration. 

