using DatenMeister.Actions;
using DatenMeister.Actions.ActionHandler;
using DatenMeister.Core.Interfaces.MOF.Reflection;
using DatenMeister.Core.Models;
using DatenMeister.Core.Provider.InMemory;
using DatenMeister.Core.Uml.Helper;
using DatenMeister.Reports.Swimlane.Model;

namespace DatenMeister.Reports.Swimlane;

public class SwimLaneViewDefinitionActionHandler : IActionHandler
{
    public bool IsResponsible(IElement node)
    {
        return node.getMetaClass()?.equals(_Root.TheOne.__SwimlaneViewDefinition) == true;
    }

    public async Task<IElement?> Evaluate(ActionLogic actionLogic, IElement action, string? actionVerb)
    {
        var actionAsObject = new Root.SwimlaneViewDefinition_Wrapper(action);
        
        if (actionVerb != "render")
        {
            // The alert result
            var result = Core.Models.Actions.ClientActions.AlertClientAction_Wrapper.Create(InMemoryObject.TemporaryFactory);
            result.messageText = "ActionHandler 'SwimLaneViewDefinitionActionHandler' just supports rendering";
            result.name = "Information";
        
            return ActionModelHelper.CreateActionResult(false, [result.GetWrappedElement()]);
        }

        var clientAction =
            DatenMeister.Core.Models.Actions.ClientActions.RenderFormClientAction_Wrapper.Create(InMemoryObject
                .TemporaryFactory);
        clientAction.formType = _Forms._FormTypes.___FormType.Decoupled;
            
        var form = Root.SwimlaneForm_Wrapper.Create(InMemoryObject.TemporaryFactory);
        form.isReadOnly = true;
        form.isAutoGenerated = true;
        var name = NamedElementMethods.GetName(action);
        form.title = string.IsNullOrEmpty(name) ? "Swimlane View" : "Swimlane: " + name;
        form.swimlaneViewDefinition = actionAsObject;

        // Finalize all the stuff
        clientAction.form = new Core.Models.Forms.FormTypes.Form_Wrapper(form.GetWrappedElement());
        return ActionModelHelper.CreateActionResult(false, [clientAction.GetWrappedElement()]);
    }
}