using DatenMeister.Actions;
using DatenMeister.Actions.ActionHandler;
using DatenMeister.Core.Interfaces.MOF.Reflection;
using DatenMeister.Core.Models;
using DatenMeister.Core.Provider.InMemory;
using DatenMeister.Core.Uml.Helper;
using DatenMeister.DataView.Forms.Model;
using DatenMeister.Forms;
using DatenMeister.Forms.FormFactory;

namespace DatenMeister.DataView.Forms;

public class ViewNodeRenderActionHandler : IActionHandler
{
    public bool IsResponsible(IElement node)
    {
        return node.getMetaClass()?.equals(
            _Root.TheOne.__ViewNodeRenderAction) == true;
    }

    public async Task<IElement?> Evaluate(ActionLogic actionLogic, IElement action, string? actionVerb)
    {
        var actionAsObject = new Root.ViewNodeRenderAction_Wrapper(action);
        
        if (actionVerb != "render")
        {
            // The alert result
            var result = Core.Models.Actions.ClientActions.AlertClientAction_Wrapper.Create(InMemoryObject.TemporaryFactory);
            result.messageText = "ActionHandler 'ViewNodeRenderActionHandler' just supports rendering";
            result.name = "Information";
        
            return ActionModelHelper.CreateActionResult(false, [result.GetWrappedElement()]);
        }

        var clientAction =
            DatenMeister.Core.Models.Actions.ClientActions.RenderFormClientAction_Wrapper.Create(InMemoryObject
                .TemporaryFactory);
        clientAction.formType = _Forms._FormTypes.___FormType.Decoupled;
            
        var form = Root.ViewDataTable_Wrapper.Create(InMemoryObject.TemporaryFactory);
        form.isReadOnly = true;
        form.isAutoGenerated = true;
        form.title = "ViewNode: " + NamedElementMethods.GetName(action);
        form.viewNode = actionAsObject.viewNode;
        
        // Gets the elements behind the viewnode
        var viewNode = form.viewNode?.GetWrappedElement() ?? throw new InvalidOperationException("Not set viewnode");
        var dataViewLogic = new DataViewLogic(actionLogic.WorkspaceLogic, actionLogic.ScopeStorage);
        
        // Gets the form itself 
        var parameter = new TableFormFactoryParameter
        {
            Collection = dataViewLogic.GetElementsForViewNode(viewNode)
        };
        
        var factory = new FormCreationContextFactory(actionLogic.WorkspaceLogic, actionLogic.ScopeStorage);
        factory.MofFactory = InMemoryObject.TemporaryFactory;
        
        var context = factory.Create(ViewModes.Default);
            
        var foundForm = FormCreation.CreateTableForm(parameter, context).Forms.FirstOrDefault();
        if(foundForm == null)
        {
            throw new InvalidOperationException("Unfortunately, we could not create the table form");
        }
        
        // Ok, now we need to get the tableform
        form.tableForm = new Core.Models.Forms.FormTypes.TableForm_Wrapper(foundForm);

        // Finalize all the stuff
        clientAction.form = new Core.Models.Forms.FormTypes.Form_Wrapper(form.GetWrappedElement());
        return ActionModelHelper.CreateActionResult(false, [clientAction.GetWrappedElement()]);
    }
}